@auth_102_HostAddress = http://localhost:5103

GET {{auth_102_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer CfDJ8FNExO7a1AxEn2L2LdGDGHKPx8vMQ0ft3ToG1uFZ5DVeWOgXDihrOm84lzFvYIYD6DOockRXPYu09eeqw-zbp0myNlRdS-tZWKf--YXbqrOaBAuToAgbmIiOrcwMkh8ntZmX2bTmJG9thSUFDvpkxo84kiB9_5WQs792AF18KYGtX7uQdeyNzGo5iA1oqIJWmRGDzjrA_2fpAKZOc4mGHXmaTyxRcp8KksUKZjr9J08YAfZHsKts_gMNz7zkre3JEVYA6X7-1_Sd_I1JBR81j9YXk7LZYAAHDEIp_SNPVpW-g_5nHkklIN3iSEozqHQO3WiBiJZAcNy_aD5kJE7qeyOxcyn3F4kYyPt6DLg-tmgxkf5vPquG7rEq5QZt4Z5iE9vRDVaiqX1FHSs3uZXIiRZt4X9olOT5LqUt3M9-IwSclpXUqxVJbd13e5yUIePROgsOp6K2lEBAd2a6OLIlnvGWR8nLB2TYNJND-peE_jEWJIe9CJaYYwrVfpH80bYHoQdNP7Jr_pPGzaQDVW5VFAtoFHJrU_pEc45k8cpV7rUOGL72Nwt06abIuUy84QQQAUKwACAfSMhyOeozdaS__IqFRcrqEGSXtK3evd7Lbi_ZD8cS0dvAjZsX8efcINXNS4_mQ3Fe__88MUEiHHesoAPUa8GXWXd0Gxk6mhHleIPDskcEO6mSpjDO8gHrXDptTA
###


POST {{auth_102_HostAddress}}/register/
Accept: application/json
Authorization: Bearer CfDJ8FNExO7a1AxEn2L2LdGDGHKPx8vMQ0ft3ToG1uFZ5DVeWOgXDihrOm84lzFvYIYD6DOockRXPYu09eeqw-zbp0myNlRdS-tZWKf--YXbqrOaBAuToAgbmIiOrcwMkh8ntZmX2bTmJG9thSUFDvpkxo84kiB9_5WQs792AF18KYGtX7uQdeyNzGo5iA1oqIJWmRGDzjrA_2fpAKZOc4mGHXmaTyxRcp8KksUKZjr9J08YAfZHsKts_gMNz7zkre3JEVYA6X7-1_Sd_I1JBR81j9YXk7LZYAAHDEIp_SNPVpW-g_5nHkklIN3iSEozqHQO3WiBiJZAcNy_aD5kJE7qeyOxcyn3F4kYyPt6DLg-tmgxkf5vPquG7rEq5QZt4Z5iE9vRDVaiqX1FHSs3uZXIiRZt4X9olOT5LqUt3M9-IwSclpXUqxVJbd13e5yUIePROgsOp6K2lEBAd2a6OLIlnvGWR8nLB2TYNJND-peE_jEWJIe9CJaYYwrVfpH80bYHoQdNP7Jr_pPGzaQDVW5VFAtoFHJrU_pEc45k8cpV7rUOGL72Nwt06abIuUy84QQQAUKwACAfSMhyOeozdaS__IqFRcrqEGSXtK3evd7Lbi_ZD8cS0dvAjZsX8efcINXNS4_mQ3Fe__88MUEiHHesoAPUa8GXWXd0Gxk6mhHleIPDskcEO6mSpjDO8gHrXDptTA
###